#! /bin/bash
# ======================================================
# Script to set up mysql DB for the simple captions API
# ======================================================

# Double check drop-database argument
if [[ $1 == 1 ]]; then
    clear
    echo """
        Are you sure you want to drop the database before proceeding? (N/y)
    """
    read choice
    if [[ ! $choice =~ y|Y|yes|Yes|YEs|YES ]]; then
        echo "OK, exiting script."
        exit 1
    fi
fi

# Load .env vars
eval $(cat .env | sed 's/^/export /')

clear
echo "
======================================
SETTING UP MYSQL DB: '"$LOCAL_DB_NAME"'
======================================
"

# Load aux functions to enable query_mysql
source _aux_functions

### 1. Drop existing DB
QUERY_DROP_DB="DROP DATABASE $LOCAL_DB_NAME;"
if [[ $1 == 1 ]]; then query_mysql $QUERY_DROP_DB; fi

### 2. Create DB if it doesn't exist
QUERY_CREATE_DB="CREATE DATABASE IF NOT EXISTS $LOCAL_DB_NAME;"
query_mysql $QUERY_CREATE_DB

### 3. Create Table schema
QUERY_CREATE_TABLES="
    USE $LOCAL_DB_NAME;
    CREATE TABLE IF NOT EXISTS Captions (
        caption_id varchar(12) NOT NULL UNIQUE PRIMARY KEY,
        caption_text varchar(350),
        caption_date varchar(20)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
"
query_mysql $QUERY_CREATE_TABLES
