#!/bin/bash

#----------------------------------------------------------------------
# POPULATE GALLERIES SCRIPT
#
# When the `galleries` dir gets created, it needs to have template
# files copied over to it. This script does that copying. It's been
# broken out into its own script for the sake of development; i.e.
# when you make changes to e.g. php_templates/phpImageGallery.php, then
# you'll want to push those changes to all of the created galleries by
# calling this script directly. This script is also called by the
# _create_gallery script, and the end user isn't expected to use it
# directly.
#----------------------------------------------------------------------

# Populate galleries root
cp php_templates/.htaccess ./galleries/
cp php_templates/.htpasswd ./galleries/
cp php_templates/captions.php ./galleries/
cp php_templates/db.php ./galleries/
cp php_templates/galleries.php ./galleries/index.php
cp php_templates/composer.json ./galleries/
ln -fs $PWD/.env galleries/.env
cat <<EOF >galleries/README.md
    This is some text
    How cool is this?
EOF

cd galleries
composer install
cd ..

# Loop through all gallery directories and add index.php (except for vendor)
for file in galleries/*; do
    if [[ -d $file ]] && [[ ! $file == 'galleries/vendor' ]]; then
        cp php_templates/gallery-index.php $file/index.php
    fi
done
